Controllers/ProveedorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SysInventory.BL;
using SysInventory.EN;
using System.Threading.Tasks;

namespace SysInventoryAppWeb.Controllers
{
    public class ProveedorController : Controller
    {
        readonly ProveedorBL _proveedorBL;
        public ProveedorController(ProveedorBL pProveedorBL)
        {
            _proveedorBL = pProveedorBL;
        }
        // GET: ProveedorController
        public async Task<ActionResult> Index()
        {
            var proveedores = await _proveedorBL.ObtenerTodosAsync();
            return View(proveedores);
        }

        // GET: ProveedorController1/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ProveedorController1/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProveedorController1/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Proveedor pProveedor)
        {
            try
            {
                var resul = await _proveedorBL.CrearAsync(pProveedor);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProveedorController1/Edit/5
        public async Task<ActionResult>  Edit(int id)
        {
            var proveedor = await _proveedorBL.ObtenerPorIdAsync(new Proveedor { Id = id });
            return View(proveedor);
        }

        // POST: ProveedorController1/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Proveedor pProveedor)
        {
            try
            {
                var resul = await _proveedorBL.ModificarAsync(pProveedor);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProveedorController1/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var proveedor = await _proveedorBL.ObtenerPorIdAsync(new Proveedor { Id = id });
            return View(proveedor);
        }

        // POST: ProveedorController1/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult>  DeleteProveedor(int id)
        {
            try
            {
                var resul = await _proveedorBL.EliminarAsync(new Proveedor { Id = id });
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Proveedor/Create.cshtml
@model Proveedor

<div class="card">
    <div class="card-header bg-primary text-white">
        <h5>Nuevo Proveedor</h5>
    </div>
    <div class="card-body">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="mb-3">
                    <label asp-for="Nombre" class="form-label"></label>
                    <input asp-for="Nombre" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="NRC" class="form-label"></label>
                    <input asp-for="NRC" class="form-control" />
                    <span asp-validation-for="NRC" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Direccion" class="form-label"></label>
                    <textarea asp-for="Direccion" class="form-control"></textarea>
                    <span asp-validation-for="Direccion" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Telefono" class="form-label"></label>
                    <input asp-for="Telefono" class="form-control" />
                    <span asp-validation-for="Telefono" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Email" class="form-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-success">Guardar</button>
            </div>
        </form>
    </div>
</div>


Views/Proveedor/Delete.cshtml
@model Proveedor

<div class="card">
    <div class="card-header bg-primary text-white">
        <h5>Editar Proveedor</h5>
    </div>
    <div class="card-body">
        <form asp-action="Edit" method="post">
            <input asp-for="Id" class="form-control" value="@Model.Id" type="hidden" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="mb-3">
                    <label asp-for="Nombre" class="form-label"></label>
                    <input asp-for="Nombre" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="NRC" class="form-label"></label>
                    <input asp-for="NRC" class="form-control" />
                    <span asp-validation-for="NRC" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Direccion" class="form-label"></label>
                    <textarea asp-for="Direccion" class="form-control"></textarea>
                    <span asp-validation-for="Direccion" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Telefono" class="form-label"></label>
                    <input asp-for="Telefono" class="form-control" />
                    <span asp-validation-for="Telefono" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Email" class="form-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <button type="submit" class="btn btn-success">Guardar Cambios</button>
        </form>
    </div>
</div>


Views/Proveedor/Edit.cshtml
@model Proveedor

<div class="card">
    <div class="card-header bg-primary text-white">
        <h5>Editar Proveedor</h5>
    </div>
    <div class="card-body">
        <form asp-action="Edit" method="post">
            <input asp-for="Id" class="form-control" value="@Model.Id" type="hidden" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="mb-3">
                    <label asp-for="Nombre" class="form-label"></label>
                    <input asp-for="Nombre" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="NRC" class="form-label"></label>
                    <input asp-for="NRC" class="form-control" />
                    <span asp-validation-for="NRC" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Direccion" class="form-label"></label>
                    <textarea asp-for="Direccion" class="form-control"></textarea>
                    <span asp-validation-for="Direccion" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Telefono" class="form-label"></label>
                    <input asp-for="Telefono" class="form-control" />
                    <span asp-validation-for="Telefono" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Email" class="form-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <button type="submit" class="btn btn-success">Guardar Cambios</button>
        </form>
    </div>
</div>

Views/Proveedor/Index.cshtml
@model List<Proveedor>
<h1>Lista de Proveedores</h1>
<div>
    <a asp-controller="Proveedor" asp-action="Create" class="btn btn-primary">Nuevo</a>
    <br />
    <br />
    @if (Model != null)
    {
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <td>Nombre</td>
                    <td>NRC</td>
                    <td>Dirección</td>
                    <td>Telefono</td>
                    <td>Email</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var proveedor in Model)
                {
                    <tr>
                        <th>@proveedor.Nombre</th>
                        <th>@proveedor.NRC</th>
                        <th>@proveedor.Direccion</th>
                        <th>@proveedor.Telefono</th>
                        <th>@proveedor.Email</th>
                        <th>
                            <a class="btn btn-primary" asp-controller="Proveedor" asp-action="Edit" asp-route-id="@proveedor.Id">Editar</a> |
                            <a class="btn btn-danger" asp-controller="Proveedor" asp-action="Delete" asp-route-id="@proveedor.Id">Eliminar</a>
                        </th>
                    </tr>
                }
            </tbody>
        </table>
    }
    }
</div>